[project]
name = "autosec-rl"
version = "0.1.0"
description = "Adaptive Cybersecurity RL Environment using OpenEnv"
authors = [
    {name = "Kumar"}
]
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-dotenv",
    "openai"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"